server {
    listen 80;
    listen [::]:80;
    server_name mda-church.com; # Substituir pelo domínio real
    root /var/www/new-church/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    index index.php;

    charset utf-8;

    # Otimização de Assets (Vite)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # Configuração PHP-FPM Otimizada
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        
        # Timeouts aumentados para relatórios PDF longos
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        
        # Buffer de saída para evitar erros 502 em respostas grandes
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # Bloqueio de arquivos sensíveis
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Cache de arquivos estáticos (Imagens/CSS/JS)
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }
}
